pipeline{
    agent any

    stages{
        stage("checkout"){
            steps{
                git url: 'https://github.com/ahmedalaa14/jenkins-project.git' ,branch: 'main'
            }
            }

        }
    stage ("setup"){
        steps{

            sh "pip install -r requirements.txt"
        }    
    }
    stage("test"){
        steps{
            sh "pytest"
        }
    }

}